/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountId = IDL.Text;
export const Time = IDL.Int;
export const License = IDL.Record({
  'active' : IDL.Bool,
  'createdAt' : Time,
  'updatedAt' : IDL.Opt(Time),
  'revokedAt' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'botPublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'accountId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'bot_id' : IDL.Opt(IDL.Text),
  'planTier' : IDL.Opt(
    IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null, 'Whale' : IDL.Null })
  ),
});
export const Status = IDL.Variant({
  'SUSPENDED' : IDL.Null,
  'ACTIVE' : IDL.Null,
});
export const HeartbeatData = IDL.Record({
  'cycles' : IDL.Nat,
  'botStatus' : Status,
  'lastHeartbeatAt' : Time,
  'verifiedLicense' : IDL.Bool,
});
export const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Trade = IDL.Record({
  'entryTimestamp' : Time,
  'accountId' : AccountId,
  'instrument' : IDL.Text,
  'side' : TradeSide,
  'size' : IDL.Float64,
  'tradeId' : IDL.Text,
  'exitTimestamp' : IDL.Opt(Time),
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Opt(IDL.Float64),
});
export const JwtToken = IDL.Record({
  'jwt' : IDL.Text,
  'accountId' : AccountId,
});
export const Error = IDL.Variant({
  'InvalidInput' : IDL.Null,
  'LicenseInactive' : IDL.Null,
  'TimestampOutOfWindow' : IDL.Null,
  'InvalidSignature' : IDL.Null,
  'Unauthorized' : IDL.Null,
  'UnknownBotId' : IDL.Null,
  'MissingBotKey' : IDL.Null,
  'ReplayDetected' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : JwtToken, 'err' : Error });
export const Symbol = IDL.Record({
  'token' : IDL.Text,
  'feed' : IDL.Text,
  'currency' : IDL.Text,
  'exchange' : IDL.Text,
});
export const Strategy = IDL.Record({
  'entryTime' : Time,
  'deployedAt' : Time,
  'name' : IDL.Text,
  'side' : TradeSide,
  'priceFeed' : Symbol,
});
export const StrategyPath = IDL.Record({
  'deployedAt' : Time,
  'items' : IDL.Vec(Strategy),
  'pathSymbols' : IDL.Vec(Symbol),
});
export const StrategyBundle = IDL.Record({
  'entryStrategy' : IDL.Nat,
  'paths' : IDL.Vec(StrategyPath),
  'items' : IDL.Vec(Strategy),
  'inputSymbol' : Symbol,
  'outputSymbol' : Symbol,
});
export const StrategicVault = IDL.Record({
  'jwt' : IDL.Text,
  'strategies' : IDL.Vec(StrategyBundle),
});
export const Result = IDL.Variant({ 'ok' : StrategicVault, 'err' : Error });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateLicense' : IDL.Func([AccountId, IDL.Bool], [], []),
  'getAllLicenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AccountId, License))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeartbeatData' : IDL.Func([AccountId], [HeartbeatData], ['query']),
  'getLicenseStatus' : IDL.Func(
      [AccountId, IDL.Vec(IDL.Nat8), IDL.Text, Time],
      [IDL.Bool],
      [],
    ),
  'getMyLicenseStatus' : IDL.Func([], [IDL.Opt(License)], ['query']),
  'getTradesPaginated' : IDL.Func(
      [IDL.Opt(AccountId), IDL.Opt(Time), IDL.Opt(Time), IDL.Nat, IDL.Nat],
      [IDL.Vec(Trade)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeLicense' : IDL.Func([AccountId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeJwt' : IDL.Func([IDL.Text, AccountId], [Result_1], []),
  'storeStrategicVault' : IDL.Func([StrategicVault, AccountId], [Result], []),
  'submitTrade' : IDL.Func([Trade, IDL.Vec(IDL.Nat8), IDL.Text, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountId = IDL.Text;
  const Time = IDL.Int;
  const License = IDL.Record({
    'active' : IDL.Bool,
    'createdAt' : Time,
    'updatedAt' : IDL.Opt(Time),
    'revokedAt' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'botPublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'accountId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'bot_id' : IDL.Opt(IDL.Text),
    'planTier' : IDL.Opt(
      IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null, 'Whale' : IDL.Null })
    ),
  });
  const Status = IDL.Variant({ 'SUSPENDED' : IDL.Null, 'ACTIVE' : IDL.Null });
  const HeartbeatData = IDL.Record({
    'cycles' : IDL.Nat,
    'botStatus' : Status,
    'lastHeartbeatAt' : Time,
    'verifiedLicense' : IDL.Bool,
  });
  const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Trade = IDL.Record({
    'entryTimestamp' : Time,
    'accountId' : AccountId,
    'instrument' : IDL.Text,
    'side' : TradeSide,
    'size' : IDL.Float64,
    'tradeId' : IDL.Text,
    'exitTimestamp' : IDL.Opt(Time),
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Opt(IDL.Float64),
  });
  const JwtToken = IDL.Record({ 'jwt' : IDL.Text, 'accountId' : AccountId });
  const Error = IDL.Variant({
    'InvalidInput' : IDL.Null,
    'LicenseInactive' : IDL.Null,
    'TimestampOutOfWindow' : IDL.Null,
    'InvalidSignature' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'UnknownBotId' : IDL.Null,
    'MissingBotKey' : IDL.Null,
    'ReplayDetected' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : JwtToken, 'err' : Error });
  const Symbol = IDL.Record({
    'token' : IDL.Text,
    'feed' : IDL.Text,
    'currency' : IDL.Text,
    'exchange' : IDL.Text,
  });
  const Strategy = IDL.Record({
    'entryTime' : Time,
    'deployedAt' : Time,
    'name' : IDL.Text,
    'side' : TradeSide,
    'priceFeed' : Symbol,
  });
  const StrategyPath = IDL.Record({
    'deployedAt' : Time,
    'items' : IDL.Vec(Strategy),
    'pathSymbols' : IDL.Vec(Symbol),
  });
  const StrategyBundle = IDL.Record({
    'entryStrategy' : IDL.Nat,
    'paths' : IDL.Vec(StrategyPath),
    'items' : IDL.Vec(Strategy),
    'inputSymbol' : Symbol,
    'outputSymbol' : Symbol,
  });
  const StrategicVault = IDL.Record({
    'jwt' : IDL.Text,
    'strategies' : IDL.Vec(StrategyBundle),
  });
  const Result = IDL.Variant({ 'ok' : StrategicVault, 'err' : Error });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateLicense' : IDL.Func([AccountId, IDL.Bool], [], []),
    'getAllLicenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AccountId, License))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeartbeatData' : IDL.Func([AccountId], [HeartbeatData], ['query']),
    'getLicenseStatus' : IDL.Func(
        [AccountId, IDL.Vec(IDL.Nat8), IDL.Text, Time],
        [IDL.Bool],
        [],
      ),
    'getMyLicenseStatus' : IDL.Func([], [IDL.Opt(License)], ['query']),
    'getTradesPaginated' : IDL.Func(
        [IDL.Opt(AccountId), IDL.Opt(Time), IDL.Opt(Time), IDL.Nat, IDL.Nat],
        [IDL.Vec(Trade)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeLicense' : IDL.Func([AccountId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeJwt' : IDL.Func([IDL.Text, AccountId], [Result_1], []),
    'storeStrategicVault' : IDL.Func([StrategicVault, AccountId], [Result], []),
    'submitTrade' : IDL.Func(
        [Trade, IDL.Vec(IDL.Nat8), IDL.Text, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };