/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = string;
export type Error = { 'InvalidInput' : null } |
  { 'LicenseInactive' : null } |
  { 'TimestampOutOfWindow' : null } |
  { 'InvalidSignature' : null } |
  { 'Unauthorized' : null } |
  { 'UnknownBotId' : null } |
  { 'MissingBotKey' : null } |
  { 'ReplayDetected' : null };
export interface HeartbeatData {
  'cycles' : bigint,
  'botStatus' : Status,
  'lastHeartbeatAt' : Time,
  'verifiedLicense' : boolean,
}
export interface JwtToken { 'jwt' : string, 'accountId' : AccountId }
export interface License {
  'active' : boolean,
  'createdAt' : Time,
  'updatedAt' : [] | [Time],
  'revokedAt' : [] | [Time],
}
export type Result = { 'ok' : StrategicVault } |
  { 'err' : Error };
export type Result_1 = { 'ok' : JwtToken } |
  { 'err' : Error };
export type Status = { 'SUSPENDED' : null } |
  { 'ACTIVE' : null };
export interface StrategicVault {
  'jwt' : string,
  'strategies' : Array<StrategyBundle>,
}
export interface Strategy {
  'entryTime' : Time,
  'deployedAt' : Time,
  'name' : string,
  'side' : TradeSide,
  'priceFeed' : Symbol,
}
export interface StrategyBundle {
  'entryStrategy' : bigint,
  'paths' : Array<StrategyPath>,
  'items' : Array<Strategy>,
  'inputSymbol' : Symbol,
  'outputSymbol' : Symbol,
}
export interface StrategyPath {
  'deployedAt' : Time,
  'items' : Array<Strategy>,
  'pathSymbols' : Array<Symbol>,
}
export interface Symbol {
  'token' : string,
  'feed' : string,
  'currency' : string,
  'exchange' : string,
}
export type Time = bigint;
export interface Trade {
  'entryTimestamp' : Time,
  'accountId' : AccountId,
  'instrument' : string,
  'side' : TradeSide,
  'size' : number,
  'tradeId' : string,
  'exitTimestamp' : [] | [Time],
  'entryPrice' : number,
  'exitPrice' : [] | [number],
}
export type TradeSide = { 'buy' : null } |
  { 'sell' : null };
export interface UserProfile {
  'botPublicKey' : [] | [Uint8Array],
  'accountId' : [] | [string],
  'name' : string,
  'bot_id' : [] | [string],
  'planTier' : [] | [{ 'Pro' : null } | { 'Free' : null } | { 'Whale' : null }],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateLicense' : ActorMethod<[AccountId, boolean], undefined>,
  'getAllLicenses' : ActorMethod<[], Array<[AccountId, License]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeartbeatData' : ActorMethod<[AccountId], HeartbeatData>,
  'getLicenseStatus' : ActorMethod<
    [AccountId, Uint8Array, string, Time],
    boolean
  >,
  'getMyLicenseStatus' : ActorMethod<[], [] | [License]>,
  'getTradesPaginated' : ActorMethod<
    [[] | [AccountId], [] | [Time], [] | [Time], bigint, bigint],
    Array<Trade>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'revokeLicense' : ActorMethod<[AccountId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeJwt' : ActorMethod<[string, AccountId], Result_1>,
  'storeStrategicVault' : ActorMethod<[StrategicVault, AccountId], Result>,
  'submitTrade' : ActorMethod<[Trade, Uint8Array, string, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];