/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UplinkStatus = IDL.Variant({
  'EXECUTE' : IDL.Null,
  'STANDBY' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AccountId = IDL.Text;
export const SubscriptionTier = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'maxApiCalls' : IDL.Nat,
  'name' : IDL.Text,
  'maxBots' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Error = IDL.Variant({
  'InvalidInput' : IDL.Null,
  'LicenseInactive' : IDL.Null,
  'TimestampOutOfWindow' : IDL.Null,
  'InvalidSignature' : IDL.Null,
  'Unauthorized' : IDL.Null,
  'UnknownBotId' : IDL.Null,
  'MissingBotKey' : IDL.Null,
  'ReplayDetected' : IDL.Null,
});
export const Result_4 = IDL.Variant({ 'ok' : SubscriptionTier, 'err' : Error });
export const Time = IDL.Int;
export const Signal = IDL.Record({
  'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'signalId' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const BotError = IDL.Variant({
  'InvalidUrl' : IDL.Text,
  'FetchFailed' : IDL.Text,
});
export const SignalFetchResult = IDL.Variant({
  'ok' : IDL.Vec(Signal),
  'err' : BotError,
});
export const License = IDL.Record({
  'active' : IDL.Bool,
  'createdAt' : Time,
  'updatedAt' : IDL.Opt(Time),
  'revokedAt' : IDL.Opt(Time),
});
export const AuditEntry = IDL.Record({
  'principal' : IDL.Principal,
  'action' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const BotProfile = IDL.Record({
  'publicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'uplinkStatus' : IDL.Bool,
  'botUrl' : IDL.Opt(IDL.Text),
  'lastHeartbeat' : Time,
  'cyclesWarning' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'timezone' : IDL.Opt(IDL.Text),
  'botPublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'notificationsEnabled' : IDL.Bool,
  'accountId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'bot_id' : IDL.Opt(IDL.Text),
  'planTier' : IDL.Opt(
    IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null, 'Whale' : IDL.Null })
  ),
});
export const Status = IDL.Variant({
  'SUSPENDED' : IDL.Null,
  'ACTIVE' : IDL.Null,
});
export const HeartbeatData = IDL.Record({
  'cycles' : IDL.Nat,
  'botStatus' : Status,
  'lastHeartbeatAt' : Time,
  'cyclesWarning' : IDL.Opt(IDL.Text),
  'verifiedLicense' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Trade = IDL.Record({
  'entryTimestamp' : Time,
  'accountId' : AccountId,
  'instrument' : IDL.Text,
  'side' : TradeSide,
  'size' : IDL.Float64,
  'tradeId' : IDL.Text,
  'exitTimestamp' : IDL.Opt(Time),
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Opt(IDL.Float64),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(SubscriptionTier),
  'err' : Error,
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const JwtToken = IDL.Record({
  'jwt' : IDL.Text,
  'accountId' : AccountId,
});
export const Result_2 = IDL.Variant({ 'ok' : JwtToken, 'err' : Error });
export const Symbol = IDL.Record({
  'token' : IDL.Text,
  'feed' : IDL.Text,
  'currency' : IDL.Text,
  'exchange' : IDL.Text,
});
export const Strategy = IDL.Record({
  'entryTime' : Time,
  'deployedAt' : Time,
  'name' : IDL.Text,
  'side' : TradeSide,
  'priceFeed' : Symbol,
});
export const StrategyPath = IDL.Record({
  'deployedAt' : Time,
  'items' : IDL.Vec(Strategy),
  'pathSymbols' : IDL.Vec(Symbol),
});
export const StrategyBundle = IDL.Record({
  'entryStrategy' : IDL.Nat,
  'paths' : IDL.Vec(StrategyPath),
  'items' : IDL.Vec(Strategy),
  'inputSymbol' : Symbol,
  'outputSymbol' : Symbol,
});
export const StrategicVault = IDL.Record({
  'jwt' : IDL.Text,
  'strategies' : IDL.Vec(StrategyBundle),
});
export const Result_1 = IDL.Variant({ 'ok' : StrategicVault, 'err' : Error });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'check_uplink' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [UplinkStatus], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateLicense' : IDL.Func([AccountId, IDL.Bool], [], []),
  'create_tier' : IDL.Func([SubscriptionTier], [Result_4], []),
  'fetchSignals' : IDL.Func([], [SignalFetchResult], []),
  'getAllLicenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AccountId, License))],
      ['query'],
    ),
  'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
  'getBotProfile' : IDL.Func([], [IDL.Opt(BotProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeartbeatData' : IDL.Func([AccountId], [HeartbeatData], ['query']),
  'getLicenseStatus' : IDL.Func(
      [AccountId, IDL.Vec(IDL.Nat8), IDL.Text, Time],
      [IDL.Bool],
      [],
    ),
  'getMyLicenseStatus' : IDL.Func([], [IDL.Opt(License)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTradesPaginated' : IDL.Func(
      [IDL.Opt(AccountId), IDL.Opt(Time), IDL.Opt(Time), IDL.Nat, IDL.Nat],
      [IDL.Vec(Trade)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'get_tier' : IDL.Func([IDL.Text], [Result_4], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'list_tiers' : IDL.Func([], [Result_3], ['query']),
  'registerBotPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'revokeLicense' : IDL.Func([AccountId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBotUrl' : IDL.Func([IDL.Text], [Result], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'storeJwt' : IDL.Func([IDL.Text, AccountId], [Result_2], []),
  'storeStrategicVault' : IDL.Func([StrategicVault, AccountId], [Result_1], []),
  'submitTrade' : IDL.Func([Trade, IDL.Vec(IDL.Nat8), IDL.Text, Time], [], []),
  'toggle_tier_active' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
  'toggle_uplink' : IDL.Func([IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'update_profile' : IDL.Func([UserProfile], [], []),
  'update_tier' : IDL.Func([IDL.Text, SubscriptionTier], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UplinkStatus = IDL.Variant({
    'EXECUTE' : IDL.Null,
    'STANDBY' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AccountId = IDL.Text;
  const SubscriptionTier = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'maxApiCalls' : IDL.Nat,
    'name' : IDL.Text,
    'maxBots' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Error = IDL.Variant({
    'InvalidInput' : IDL.Null,
    'LicenseInactive' : IDL.Null,
    'TimestampOutOfWindow' : IDL.Null,
    'InvalidSignature' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'UnknownBotId' : IDL.Null,
    'MissingBotKey' : IDL.Null,
    'ReplayDetected' : IDL.Null,
  });
  const Result_4 = IDL.Variant({ 'ok' : SubscriptionTier, 'err' : Error });
  const Time = IDL.Int;
  const Signal = IDL.Record({
    'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'signalId' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const BotError = IDL.Variant({
    'InvalidUrl' : IDL.Text,
    'FetchFailed' : IDL.Text,
  });
  const SignalFetchResult = IDL.Variant({
    'ok' : IDL.Vec(Signal),
    'err' : BotError,
  });
  const License = IDL.Record({
    'active' : IDL.Bool,
    'createdAt' : Time,
    'updatedAt' : IDL.Opt(Time),
    'revokedAt' : IDL.Opt(Time),
  });
  const AuditEntry = IDL.Record({
    'principal' : IDL.Principal,
    'action' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const BotProfile = IDL.Record({
    'publicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'uplinkStatus' : IDL.Bool,
    'botUrl' : IDL.Opt(IDL.Text),
    'lastHeartbeat' : Time,
    'cyclesWarning' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'timezone' : IDL.Opt(IDL.Text),
    'botPublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'notificationsEnabled' : IDL.Bool,
    'accountId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'bot_id' : IDL.Opt(IDL.Text),
    'planTier' : IDL.Opt(
      IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null, 'Whale' : IDL.Null })
    ),
  });
  const Status = IDL.Variant({ 'SUSPENDED' : IDL.Null, 'ACTIVE' : IDL.Null });
  const HeartbeatData = IDL.Record({
    'cycles' : IDL.Nat,
    'botStatus' : Status,
    'lastHeartbeatAt' : Time,
    'cyclesWarning' : IDL.Opt(IDL.Text),
    'verifiedLicense' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Trade = IDL.Record({
    'entryTimestamp' : Time,
    'accountId' : AccountId,
    'instrument' : IDL.Text,
    'side' : TradeSide,
    'size' : IDL.Float64,
    'tradeId' : IDL.Text,
    'exitTimestamp' : IDL.Opt(Time),
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Opt(IDL.Float64),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Vec(SubscriptionTier),
    'err' : Error,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const JwtToken = IDL.Record({ 'jwt' : IDL.Text, 'accountId' : AccountId });
  const Result_2 = IDL.Variant({ 'ok' : JwtToken, 'err' : Error });
  const Symbol = IDL.Record({
    'token' : IDL.Text,
    'feed' : IDL.Text,
    'currency' : IDL.Text,
    'exchange' : IDL.Text,
  });
  const Strategy = IDL.Record({
    'entryTime' : Time,
    'deployedAt' : Time,
    'name' : IDL.Text,
    'side' : TradeSide,
    'priceFeed' : Symbol,
  });
  const StrategyPath = IDL.Record({
    'deployedAt' : Time,
    'items' : IDL.Vec(Strategy),
    'pathSymbols' : IDL.Vec(Symbol),
  });
  const StrategyBundle = IDL.Record({
    'entryStrategy' : IDL.Nat,
    'paths' : IDL.Vec(StrategyPath),
    'items' : IDL.Vec(Strategy),
    'inputSymbol' : Symbol,
    'outputSymbol' : Symbol,
  });
  const StrategicVault = IDL.Record({
    'jwt' : IDL.Text,
    'strategies' : IDL.Vec(StrategyBundle),
  });
  const Result_1 = IDL.Variant({ 'ok' : StrategicVault, 'err' : Error });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'check_uplink' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [UplinkStatus],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateLicense' : IDL.Func([AccountId, IDL.Bool], [], []),
    'create_tier' : IDL.Func([SubscriptionTier], [Result_4], []),
    'fetchSignals' : IDL.Func([], [SignalFetchResult], []),
    'getAllLicenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AccountId, License))],
        ['query'],
      ),
    'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
    'getBotProfile' : IDL.Func([], [IDL.Opt(BotProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeartbeatData' : IDL.Func([AccountId], [HeartbeatData], ['query']),
    'getLicenseStatus' : IDL.Func(
        [AccountId, IDL.Vec(IDL.Nat8), IDL.Text, Time],
        [IDL.Bool],
        [],
      ),
    'getMyLicenseStatus' : IDL.Func([], [IDL.Opt(License)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTradesPaginated' : IDL.Func(
        [IDL.Opt(AccountId), IDL.Opt(Time), IDL.Opt(Time), IDL.Nat, IDL.Nat],
        [IDL.Vec(Trade)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'get_tier' : IDL.Func([IDL.Text], [Result_4], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'list_tiers' : IDL.Func([], [Result_3], ['query']),
    'registerBotPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'revokeLicense' : IDL.Func([AccountId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBotUrl' : IDL.Func([IDL.Text], [Result], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'storeJwt' : IDL.Func([IDL.Text, AccountId], [Result_2], []),
    'storeStrategicVault' : IDL.Func(
        [StrategicVault, AccountId],
        [Result_1],
        [],
      ),
    'submitTrade' : IDL.Func(
        [Trade, IDL.Vec(IDL.Nat8), IDL.Text, Time],
        [],
        [],
      ),
    'toggle_tier_active' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
    'toggle_uplink' : IDL.Func([IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'update_profile' : IDL.Func([UserProfile], [], []),
    'update_tier' : IDL.Func([IDL.Text, SubscriptionTier], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };