/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = string;
export interface AnalyticsEvent {
  'id' : [] | [string],
  'principal' : [] | [Principal],
  'count' : bigint,
  'timestamp' : bigint,
  'elementId' : string,
  'payload' : [] | [string],
  'eventType' : EventType,
}
export interface AuditEntry {
  'principal' : Principal,
  'action' : string,
  'timestamp' : Time,
  'details' : string,
}
export type BotError = { 'InvalidUrl' : string } |
  { 'FetchFailed' : string };
export interface BotProfile {
  'publicKey' : [] | [Uint8Array],
  'uplinkStatus' : boolean,
  'botUrl' : [] | [string],
  'lastHeartbeat' : Time,
  'cyclesWarning' : boolean,
}
export type Error = { 'InvalidInput' : null } |
  { 'LicenseInactive' : null } |
  { 'TimestampOutOfWindow' : null } |
  { 'InvalidSignature' : null } |
  { 'Unauthorized' : null } |
  { 'UnknownBotId' : null } |
  { 'MissingBotKey' : null } |
  { 'ReplayDetected' : null };
export type EventType = { 'Started' : null } |
  { 'Tour' : null } |
  { 'Navigation' : null } |
  { 'Stripe' : null } |
  { 'Completed' : null };
export interface HeartbeatData {
  'cycles' : bigint,
  'botStatus' : Status,
  'lastHeartbeatAt' : Time,
  'cyclesWarning' : [] | [string],
  'verifiedLicense' : boolean,
}
export interface JwtToken { 'jwt' : string, 'accountId' : AccountId }
export interface License {
  'active' : boolean,
  'createdAt' : Time,
  'updatedAt' : [] | [Time],
  'revokedAt' : [] | [Time],
}
export type Result = { 'ok' : string } |
  { 'err' : Error };
export type Result_1 = { 'ok' : StrategicVault } |
  { 'err' : Error };
export type Result_2 = { 'ok' : JwtToken } |
  { 'err' : Error };
export type Result_3 = { 'ok' : Array<SubscriptionTier> } |
  { 'err' : Error };
export type Result_4 = { 'ok' : SubscriptionTier } |
  { 'err' : Error };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SignalFetchResult = {
    'ok' : { 'body' : string, 'timestamp' : bigint, 'statusCode' : bigint }
  } |
  { 'err' : BotError };
export type Status = { 'SUSPENDED' : null } |
  { 'ACTIVE' : null };
export interface StrategicVault {
  'jwt' : string,
  'strategies' : Array<StrategyBundle>,
}
export interface Strategy {
  'entryTime' : Time,
  'deployedAt' : Time,
  'name' : string,
  'side' : TradeSide,
  'priceFeed' : Symbol,
}
export interface StrategyBundle {
  'entryStrategy' : bigint,
  'paths' : Array<StrategyPath>,
  'items' : Array<Strategy>,
  'inputSymbol' : Symbol,
  'outputSymbol' : Symbol,
}
export interface StrategyPath {
  'deployedAt' : Time,
  'items' : Array<Strategy>,
  'pathSymbols' : Array<Symbol>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionTier {
  'id' : string,
  'features' : Array<string>,
  'active' : boolean,
  'maxApiCalls' : bigint,
  'name' : string,
  'maxBots' : bigint,
  'priceInCents' : bigint,
}
export interface Symbol {
  'token' : string,
  'feed' : string,
  'currency' : string,
  'exchange' : string,
}
export type Time = bigint;
export interface Trade {
  'entryTimestamp' : Time,
  'accountId' : AccountId,
  'instrument' : string,
  'side' : TradeSide,
  'size' : number,
  'tradeId' : string,
  'exitTimestamp' : [] | [Time],
  'entryPrice' : number,
  'exitPrice' : [] | [number],
}
export type TradeSide = { 'buy' : null } |
  { 'sell' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UplinkStatus = { 'EXECUTE' : null } |
  { 'STANDBY' : null };
export interface UserProfile {
  'timezone' : [] | [string],
  'botPublicKey' : [] | [Uint8Array],
  'notificationsEnabled' : boolean,
  'accountId' : [] | [string],
  'name' : string,
  'bot_id' : [] | [string],
  'planTier' : [] | [{ 'Pro' : null } | { 'Free' : null } | { 'Whale' : null }],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'check_uplink' : ActorMethod<[string, Uint8Array], UplinkStatus>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateLicense' : ActorMethod<[AccountId, boolean], undefined>,
  'create_tier' : ActorMethod<[SubscriptionTier], Result_4>,
  'fetchSignals' : ActorMethod<[], SignalFetchResult>,
  'getAllLicenses' : ActorMethod<[], Array<[AccountId, License]>>,
  'getAnalyticsEvents' : ActorMethod<[bigint], Array<AnalyticsEvent>>,
  'getAnalyticsEventsForRange' : ActorMethod<
    [[] | [bigint], [] | [bigint], bigint],
    Array<AnalyticsEvent>
  >,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getBotProfile' : ActorMethod<[], [] | [BotProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventTypeClass' : ActorMethod<[EventType], [] | [string]>,
  'getHeartbeatData' : ActorMethod<[AccountId], HeartbeatData>,
  'getLicenseStatus' : ActorMethod<
    [AccountId, Uint8Array, string, Time],
    boolean
  >,
  'getMyLicenseStatus' : ActorMethod<[], [] | [License]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTradesPaginated' : ActorMethod<
    [[] | [AccountId], [] | [Time], [] | [Time], bigint, bigint],
    Array<Trade>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'get_tier' : ActorMethod<[string], Result_4>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'list_tiers' : ActorMethod<[], Result_3>,
  'registerBotPublicKey' : ActorMethod<[Uint8Array], undefined>,
  'revokeLicense' : ActorMethod<[AccountId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBotUrl' : ActorMethod<[string], Result>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storeAnalyticsEvent' : ActorMethod<
    [[] | [string], EventType, string, bigint, [] | [string]],
    undefined
  >,
  'storeJwt' : ActorMethod<[string, AccountId], Result_2>,
  'storeStrategicVault' : ActorMethod<[StrategicVault, AccountId], Result_1>,
  'submitTrade' : ActorMethod<[Trade, Uint8Array, string, Time], undefined>,
  'toggle_tier_active' : ActorMethod<[string, boolean], Result>,
  'toggle_uplink' : ActorMethod<[boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'update_tier' : ActorMethod<[string, SubscriptionTier], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];