/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Symbol {
    token: string;
    feed: string;
    currency: string;
    exchange: string;
}
export type Time = bigint;
export interface Trade {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
}
export interface StrategyBundle {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
}
export type Result_1 = {
    __kind__: "ok";
    ok: JwtToken;
} | {
    __kind__: "err";
    err: Error_;
};
export interface HeartbeatData {
    cycles: bigint;
    botStatus: Status;
    lastHeartbeatAt: Time;
    verifiedLicense: boolean;
}
export interface StrategicVault {
    jwt: string;
    strategies: Array<StrategyBundle>;
}
export type AccountId = string;
export type Result = {
    __kind__: "ok";
    ok: StrategicVault;
} | {
    __kind__: "err";
    err: Error_;
};
export interface License {
    active: boolean;
    createdAt: Time;
    updatedAt?: Time;
    revokedAt?: Time;
}
export interface JwtToken {
    jwt: string;
    accountId: AccountId;
}
export interface StrategyPath {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
}
export interface Strategy {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
}
export interface UserProfile {
    botPublicKey?: Uint8Array;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
}
export enum Error_ {
    InvalidInput = "InvalidInput",
    LicenseInactive = "LicenseInactive",
    TimestampOutOfWindow = "TimestampOutOfWindow",
    InvalidSignature = "InvalidSignature",
    Unauthorized = "Unauthorized",
    UnknownBotId = "UnknownBotId",
    MissingBotKey = "MissingBotKey",
    ReplayDetected = "ReplayDetected"
}
export enum Status {
    SUSPENDED = "SUSPENDED",
    ACTIVE = "ACTIVE"
}
export enum TradeSide {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Pro_Free_Whale {
    Pro = "Pro",
    Free = "Free",
    Whale = "Whale"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateLicense(accountId: AccountId, active: boolean): Promise<void>;
    getAllLicenses(): Promise<Array<[AccountId, License]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHeartbeatData(_accountId: AccountId): Promise<HeartbeatData>;
    getLicenseStatus(accountId: AccountId, signature: Uint8Array, nonce: string, timestamp: Time): Promise<boolean>;
    getMyLicenseStatus(): Promise<License | null>;
    getTradesPaginated(accountId: AccountId | null, startTime: Time | null, endTime: Time | null, start: bigint, limit: bigint): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    revokeLicense(accountId: AccountId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeJwt(jwt: string, accountId: AccountId): Promise<Result_1>;
    storeStrategicVault(vaultData: StrategicVault, _accountId: AccountId): Promise<Result>;
    submitTrade(trade: Trade, signature: Uint8Array, nonce: string, timestamp: Time): Promise<void>;
}
import type { AccountId as _AccountId, Error as _Error, HeartbeatData as _HeartbeatData, JwtToken as _JwtToken, License as _License, Result as _Result, Result_1 as _Result_1, Status as _Status, StrategicVault as _StrategicVault, Strategy as _Strategy, StrategyBundle as _StrategyBundle, StrategyPath as _StrategyPath, Symbol as _Symbol, Time as _Time, Trade as _Trade, TradeSide as _TradeSide, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateLicense(arg0: AccountId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateLicense(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateLicense(arg0, arg1);
            return result;
        }
    }
    async getAllLicenses(): Promise<Array<[AccountId, License]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLicenses();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLicenses();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeartbeatData(arg0: AccountId): Promise<HeartbeatData> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeartbeatData(arg0);
                return from_candid_HeartbeatData_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeartbeatData(arg0);
            return from_candid_HeartbeatData_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLicenseStatus(arg0: AccountId, arg1: Uint8Array, arg2: string, arg3: Time): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getLicenseStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLicenseStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getMyLicenseStatus(): Promise<License | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLicenseStatus();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLicenseStatus();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesPaginated(arg0: AccountId | null, arg1: Time | null, arg2: Time | null, arg3: bigint, arg4: bigint): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesPaginated(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesPaginated(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async revokeLicense(arg0: AccountId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeLicense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeLicense(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async storeJwt(arg0: string, arg1: AccountId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.storeJwt(arg0, arg1);
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeJwt(arg0, arg1);
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeStrategicVault(arg0: StrategicVault, arg1: AccountId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.storeStrategicVault(to_candid_StrategicVault_n37(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeStrategicVault(to_candid_StrategicVault_n37(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTrade(arg0: Trade, arg1: Uint8Array, arg2: string, arg3: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTrade(to_candid_Trade_n63(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTrade(to_candid_Trade_n63(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Error_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_HeartbeatData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeartbeatData): HeartbeatData {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_License_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _License): License {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StrategicVault_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategicVault): StrategicVault {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_StrategyBundle_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategyBundle): StrategyBundle {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_StrategyPath_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategyPath): StrategyPath {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSide_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSide): TradeSide {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        Pro: null;
    } | {
        Free: null;
    } | {
        Whale: null;
    }]): Variant_Pro_Free_Whale | null {
    return value.length === 0 ? null : from_candid_variant_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_License]): License | null {
    return value.length === 0 ? null : from_candid_License_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    botPublicKey: [] | [Uint8Array];
    accountId: [] | [string];
    name: string;
    bot_id: [] | [string];
    planTier: [] | [{
            Pro: null;
        } | {
            Free: null;
        } | {
            Whale: null;
        }];
}): {
    botPublicKey?: Uint8Array;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
} {
    return {
        botPublicKey: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.botPublicKey)),
        accountId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.accountId)),
        name: value.name,
        bot_id: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.bot_id)),
        planTier: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.planTier))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cycles: bigint;
    botStatus: _Status;
    lastHeartbeatAt: _Time;
    verifiedLicense: boolean;
}): {
    cycles: bigint;
    botStatus: Status;
    lastHeartbeatAt: Time;
    verifiedLicense: boolean;
} {
    return {
        cycles: value.cycles,
        botStatus: from_candid_Status_n19(_uploadFile, _downloadFile, value.botStatus),
        lastHeartbeatAt: value.lastHeartbeatAt,
        verifiedLicense: value.verifiedLicense
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTimestamp: _Time;
    accountId: _AccountId;
    instrument: string;
    side: _TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp: [] | [_Time];
    entryPrice: number;
    exitPrice: [] | [number];
}): {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
} {
    return {
        entryTimestamp: value.entryTimestamp,
        accountId: value.accountId,
        instrument: value.instrument,
        side: from_candid_TradeSide_n27(_uploadFile, _downloadFile, value.side),
        size: value.size,
        tradeId: value.tradeId,
        exitTimestamp: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.exitTimestamp)),
        entryPrice: value.entryPrice,
        exitPrice: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.exitPrice))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jwt: string;
    strategies: Array<_StrategyBundle>;
}): {
    jwt: string;
    strategies: Array<StrategyBundle>;
} {
    return {
        jwt: value.jwt,
        strategies: from_candid_vec_n54(_uploadFile, _downloadFile, value.strategies)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryStrategy: bigint;
    paths: Array<_StrategyPath>;
    items: Array<_Strategy>;
    inputSymbol: _Symbol;
    outputSymbol: _Symbol;
}): {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
} {
    return {
        entryStrategy: value.entryStrategy,
        paths: from_candid_vec_n57(_uploadFile, _downloadFile, value.paths),
        items: from_candid_vec_n60(_uploadFile, _downloadFile, value.items),
        inputSymbol: value.inputSymbol,
        outputSymbol: value.outputSymbol
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployedAt: _Time;
    items: Array<_Strategy>;
    pathSymbols: Array<_Symbol>;
}): {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
} {
    return {
        deployedAt: value.deployedAt,
        items: from_candid_vec_n60(_uploadFile, _downloadFile, value.items),
        pathSymbols: value.pathSymbols
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    createdAt: _Time;
    updatedAt: [] | [_Time];
    revokedAt: [] | [_Time];
}): {
    active: boolean;
    createdAt: Time;
    updatedAt?: Time;
    revokedAt?: Time;
} {
    return {
        active: value.active,
        createdAt: value.createdAt,
        updatedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.updatedAt)),
        revokedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.revokedAt))
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTime: _Time;
    deployedAt: _Time;
    name: string;
    side: _TradeSide;
    priceFeed: _Symbol;
}): {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
} {
    return {
        entryTime: value.entryTime,
        deployedAt: value.deployedAt,
        name: value.name,
        side: from_candid_TradeSide_n27(_uploadFile, _downloadFile, value.side),
        priceFeed: value.priceFeed
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AccountId, _License]): [AccountId, License] {
    return [
        value[0],
        from_candid_License_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Free: null;
} | {
    Whale: null;
}): Variant_Pro_Free_Whale {
    return "Pro" in value ? Variant_Pro_Free_Whale.Pro : "Free" in value ? Variant_Pro_Free_Whale.Free : "Whale" in value ? Variant_Pro_Free_Whale.Whale : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SUSPENDED: null;
} | {
    ACTIVE: null;
}): Status {
    return "SUSPENDED" in value ? Status.SUSPENDED : "ACTIVE" in value ? Status.ACTIVE : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeSide {
    return "buy" in value ? TradeSide.buy : "sell" in value ? TradeSide.sell : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JwtToken;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: JwtToken;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InvalidInput: null;
} | {
    LicenseInactive: null;
} | {
    TimestampOutOfWindow: null;
} | {
    InvalidSignature: null;
} | {
    Unauthorized: null;
} | {
    UnknownBotId: null;
} | {
    MissingBotKey: null;
} | {
    ReplayDetected: null;
}): Error_ {
    return "InvalidInput" in value ? Error.InvalidInput : "LicenseInactive" in value ? Error.LicenseInactive : "TimestampOutOfWindow" in value ? Error.TimestampOutOfWindow : "InvalidSignature" in value ? Error.InvalidSignature : "Unauthorized" in value ? Error.Unauthorized : "UnknownBotId" in value ? Error.UnknownBotId : "MissingBotKey" in value ? Error.MissingBotKey : "ReplayDetected" in value ? Error.ReplayDetected : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StrategicVault;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: StrategicVault;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StrategicVault_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AccountId, _License]>): Array<[AccountId, License]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrategyBundle>): Array<StrategyBundle> {
    return value.map((x)=>from_candid_StrategyBundle_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrategyPath>): Array<StrategyPath> {
    return value.map((x)=>from_candid_StrategyPath_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Strategy>): Array<Strategy> {
    return value.map((x)=>from_candid_Strategy_n61(_uploadFile, _downloadFile, x));
}
function to_candid_StrategicVault_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategicVault): _StrategicVault {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_StrategyBundle_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategyBundle): _StrategyBundle {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_StrategyPath_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategyPath): _StrategyPath {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Strategy_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_TradeSide_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): _TradeSide {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountId | null): [] | [_AccountId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    botPublicKey?: Uint8Array;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
}): {
    botPublicKey: [] | [Uint8Array];
    accountId: [] | [string];
    name: string;
    bot_id: [] | [string];
    planTier: [] | [{
            Pro: null;
        } | {
            Free: null;
        } | {
            Whale: null;
        }];
} {
    return {
        botPublicKey: value.botPublicKey ? candid_some(value.botPublicKey) : candid_none(),
        accountId: value.accountId ? candid_some(value.accountId) : candid_none(),
        name: value.name,
        bot_id: value.bot_id ? candid_some(value.bot_id) : candid_none(),
        planTier: value.planTier ? candid_some(to_candid_variant_n32(_uploadFile, _downloadFile, value.planTier)) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jwt: string;
    strategies: Array<StrategyBundle>;
}): {
    jwt: string;
    strategies: Array<_StrategyBundle>;
} {
    return {
        jwt: value.jwt,
        strategies: to_candid_vec_n39(_uploadFile, _downloadFile, value.strategies)
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
}): {
    entryStrategy: bigint;
    paths: Array<_StrategyPath>;
    items: Array<_Strategy>;
    inputSymbol: _Symbol;
    outputSymbol: _Symbol;
} {
    return {
        entryStrategy: value.entryStrategy,
        paths: to_candid_vec_n42(_uploadFile, _downloadFile, value.paths),
        items: to_candid_vec_n45(_uploadFile, _downloadFile, value.items),
        inputSymbol: value.inputSymbol,
        outputSymbol: value.outputSymbol
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
}): {
    deployedAt: _Time;
    items: Array<_Strategy>;
    pathSymbols: Array<_Symbol>;
} {
    return {
        deployedAt: value.deployedAt,
        items: to_candid_vec_n45(_uploadFile, _downloadFile, value.items),
        pathSymbols: value.pathSymbols
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
}): {
    entryTime: _Time;
    deployedAt: _Time;
    name: string;
    side: _TradeSide;
    priceFeed: _Symbol;
} {
    return {
        entryTime: value.entryTime,
        deployedAt: value.deployedAt,
        name: value.name,
        side: to_candid_TradeSide_n48(_uploadFile, _downloadFile, value.side),
        priceFeed: value.priceFeed
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
}): {
    entryTimestamp: _Time;
    accountId: _AccountId;
    instrument: string;
    side: _TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp: [] | [_Time];
    entryPrice: number;
    exitPrice: [] | [number];
} {
    return {
        entryTimestamp: value.entryTimestamp,
        accountId: value.accountId,
        instrument: value.instrument,
        side: to_candid_TradeSide_n48(_uploadFile, _downloadFile, value.side),
        size: value.size,
        tradeId: value.tradeId,
        exitTimestamp: value.exitTimestamp ? candid_some(value.exitTimestamp) : candid_none(),
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Pro_Free_Whale): {
    Pro: null;
} | {
    Free: null;
} | {
    Whale: null;
} {
    return value == Variant_Pro_Free_Whale.Pro ? {
        Pro: null
    } : value == Variant_Pro_Free_Whale.Free ? {
        Free: null
    } : value == Variant_Pro_Free_Whale.Whale ? {
        Whale: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeSide.buy ? {
        buy: null
    } : value == TradeSide.sell ? {
        sell: null
    } : value;
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StrategyBundle>): Array<_StrategyBundle> {
    return value.map((x)=>to_candid_StrategyBundle_n40(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StrategyPath>): Array<_StrategyPath> {
    return value.map((x)=>to_candid_StrategyPath_n43(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Strategy>): Array<_Strategy> {
    return value.map((x)=>to_candid_Strategy_n46(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
