/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: JwtToken;
} | {
    __kind__: "err";
    err: Error_;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface StrategyBundle {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
}
export interface AuditEntry {
    principal: Principal;
    action: string;
    timestamp: Time;
    details: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: StrategicVault;
} | {
    __kind__: "err";
    err: Error_;
};
export interface HeartbeatData {
    cycles: bigint;
    botStatus: Status;
    lastHeartbeatAt: Time;
    cyclesWarning?: string;
    verifiedLicense: boolean;
}
export interface StrategicVault {
    jwt: string;
    strategies: Array<StrategyBundle>;
}
export type Result_4 = {
    __kind__: "ok";
    ok: SubscriptionTier;
} | {
    __kind__: "err";
    err: Error_;
};
export type AccountId = string;
export interface License {
    active: boolean;
    createdAt: Time;
    updatedAt?: Time;
    revokedAt?: Time;
}
export type SignalFetchResult = {
    __kind__: "ok";
    ok: {
        body: string;
        timestamp: bigint;
        statusCode: bigint;
    };
} | {
    __kind__: "err";
    err: BotError;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StrategyPath {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Strategy {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
}
export interface Symbol {
    token: string;
    feed: string;
    currency: string;
    exchange: string;
}
export interface BotProfile {
    publicKey?: Uint8Array;
    uplinkStatus: boolean;
    botUrl?: string;
    lastHeartbeat: Time;
    cyclesWarning: boolean;
}
export interface Trade {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SubscriptionTier {
    id: string;
    features: Array<string>;
    active: boolean;
    maxApiCalls: bigint;
    name: string;
    maxBots: bigint;
    priceInCents: bigint;
}
export interface JwtToken {
    jwt: string;
    accountId: AccountId;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Result_3 = {
    __kind__: "ok";
    ok: Array<SubscriptionTier>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: Error_;
};
export type BotError = {
    __kind__: "InvalidUrl";
    InvalidUrl: string;
} | {
    __kind__: "FetchFailed";
    FetchFailed: string;
};
export interface UserProfile {
    timezone?: string;
    botPublicKey?: Uint8Array;
    notificationsEnabled: boolean;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
}
export enum Error_ {
    InvalidInput = "InvalidInput",
    LicenseInactive = "LicenseInactive",
    TimestampOutOfWindow = "TimestampOutOfWindow",
    InvalidSignature = "InvalidSignature",
    Unauthorized = "Unauthorized",
    UnknownBotId = "UnknownBotId",
    MissingBotKey = "MissingBotKey",
    ReplayDetected = "ReplayDetected"
}
export enum Status {
    SUSPENDED = "SUSPENDED",
    ACTIVE = "ACTIVE"
}
export enum TradeSide {
    buy = "buy",
    sell = "sell"
}
export enum UplinkStatus {
    EXECUTE = "EXECUTE",
    STANDBY = "STANDBY"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Pro_Free_Whale {
    Pro = "Pro",
    Free = "Free",
    Whale = "Whale"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    check_uplink(bot_id: string, signature: Uint8Array): Promise<UplinkStatus>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrUpdateLicense(accountId: AccountId, active: boolean): Promise<void>;
    create_tier(tier: SubscriptionTier): Promise<Result_4>;
    fetchSignals(): Promise<SignalFetchResult>;
    getAllLicenses(): Promise<Array<[AccountId, License]>>;
    getAuditLog(limit: bigint): Promise<Array<AuditEntry>>;
    getBotProfile(): Promise<BotProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHeartbeatData(_accountId: AccountId): Promise<HeartbeatData>;
    getLicenseStatus(accountId: AccountId, signature: Uint8Array, nonce: string, timestamp: Time): Promise<boolean>;
    getMyLicenseStatus(): Promise<License | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTradesPaginated(accountId: AccountId | null, startTime: Time | null, endTime: Time | null, start: bigint, limit: bigint): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    get_tier(id: string): Promise<Result_4>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    list_tiers(): Promise<Result_3>;
    registerBotPublicKey(publicKey: Uint8Array): Promise<void>;
    revokeLicense(accountId: AccountId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBotUrl(url: string): Promise<Result>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    storeJwt(jwt: string, accountId: AccountId): Promise<Result_2>;
    storeStrategicVault(vaultData: StrategicVault, _accountId: AccountId): Promise<Result_1>;
    submitTrade(trade: Trade, signature: Uint8Array, nonce: string, timestamp: Time): Promise<void>;
    toggle_tier_active(id: string, active: boolean): Promise<Result>;
    toggle_uplink(state: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    update_profile(profile: UserProfile): Promise<void>;
    update_tier(id: string, updated: SubscriptionTier): Promise<Result>;
}
import type { AccountId as _AccountId, BotError as _BotError, BotProfile as _BotProfile, Error as _Error, HeartbeatData as _HeartbeatData, JwtToken as _JwtToken, License as _License, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, SignalFetchResult as _SignalFetchResult, Status as _Status, StrategicVault as _StrategicVault, Strategy as _Strategy, StrategyBundle as _StrategyBundle, StrategyPath as _StrategyPath, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, Symbol as _Symbol, Time as _Time, Trade as _Trade, TradeSide as _TradeSide, UplinkStatus as _UplinkStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async check_uplink(arg0: string, arg1: Uint8Array): Promise<UplinkStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.check_uplink(arg0, arg1);
                return from_candid_UplinkStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.check_uplink(arg0, arg1);
            return from_candid_UplinkStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateLicense(arg0: AccountId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateLicense(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateLicense(arg0, arg1);
            return result;
        }
    }
    async create_tier(arg0: SubscriptionTier): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.create_tier(arg0);
                return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_tier(arg0);
            return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchSignals(): Promise<SignalFetchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSignals();
                return from_candid_SignalFetchResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSignals();
            return from_candid_SignalFetchResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLicenses(): Promise<Array<[AccountId, License]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLicenses();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLicenses();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0);
            return result;
        }
    }
    async getBotProfile(): Promise<BotProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBotProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBotProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeartbeatData(arg0: AccountId): Promise<HeartbeatData> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeartbeatData(arg0);
                return from_candid_HeartbeatData_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeartbeatData(arg0);
            return from_candid_HeartbeatData_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLicenseStatus(arg0: AccountId, arg1: Uint8Array, arg2: string, arg3: Time): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getLicenseStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLicenseStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getMyLicenseStatus(): Promise<License | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLicenseStatus();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLicenseStatus();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesPaginated(arg0: AccountId | null, arg1: Time | null, arg2: Time | null, arg3: bigint, arg4: bigint): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesPaginated(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesPaginated(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_tier(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.get_tier(arg0);
                return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_tier(arg0);
            return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async list_tiers(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.list_tiers();
                return from_candid_Result_3_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_tiers();
            return from_candid_Result_3_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerBotPublicKey(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBotPublicKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBotPublicKey(arg0);
            return result;
        }
    }
    async revokeLicense(arg0: AccountId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeLicense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeLicense(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setBotUrl(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setBotUrl(arg0);
                return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBotUrl(arg0);
            return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async storeJwt(arg0: string, arg1: AccountId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.storeJwt(arg0, arg1);
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeJwt(arg0, arg1);
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeStrategicVault(arg0: StrategicVault, arg1: AccountId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.storeStrategicVault(to_candid_StrategicVault_n55(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_1_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeStrategicVault(to_candid_StrategicVault_n55(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_1_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTrade(arg0: Trade, arg1: Uint8Array, arg2: string, arg3: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTrade(to_candid_Trade_n81(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTrade(to_candid_Trade_n81(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async toggle_tier_active(arg0: string, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.toggle_tier_active(arg0, arg1);
                return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggle_tier_active(arg0, arg1);
            return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggle_uplink(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggle_uplink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggle_uplink(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async update_profile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_profile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_profile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async update_tier(arg0: string, arg1: SubscriptionTier): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.update_tier(arg0, arg1);
                return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_tier(arg0, arg1);
            return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BotError_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotError): BotError {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BotProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotProfile): BotProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_HeartbeatData_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeartbeatData): HeartbeatData {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_License_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _License): License {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_SignalFetchResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalFetchResult): SignalFetchResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_StrategicVault_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategicVault): StrategicVault {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_StrategyBundle_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategyBundle): StrategyBundle {
    return from_candid_record_n74(_uploadFile, _downloadFile, value);
}
function from_candid_StrategyPath_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategyPath): StrategyPath {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSide_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSide): TradeSide {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UplinkStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UplinkStatus): UplinkStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BotProfile]): BotProfile | null {
    return value.length === 0 ? null : from_candid_BotProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        Pro: null;
    } | {
        Free: null;
    } | {
        Whale: null;
    }]): Variant_Pro_Free_Whale | null {
    return value.length === 0 ? null : from_candid_variant_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_License]): License | null {
    return value.length === 0 ? null : from_candid_License_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    createdAt: _Time;
    updatedAt: [] | [_Time];
    revokedAt: [] | [_Time];
}): {
    active: boolean;
    createdAt: Time;
    updatedAt?: Time;
    revokedAt?: Time;
} {
    return {
        active: value.active,
        createdAt: value.createdAt,
        updatedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.updatedAt)),
        revokedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.revokedAt))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicKey: [] | [Uint8Array];
    uplinkStatus: boolean;
    botUrl: [] | [string];
    lastHeartbeat: _Time;
    cyclesWarning: boolean;
}): {
    publicKey?: Uint8Array;
    uplinkStatus: boolean;
    botUrl?: string;
    lastHeartbeat: Time;
    cyclesWarning: boolean;
} {
    return {
        publicKey: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.publicKey)),
        uplinkStatus: value.uplinkStatus,
        botUrl: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.botUrl)),
        lastHeartbeat: value.lastHeartbeat,
        cyclesWarning: value.cyclesWarning
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone: [] | [string];
    botPublicKey: [] | [Uint8Array];
    notificationsEnabled: boolean;
    accountId: [] | [string];
    name: string;
    bot_id: [] | [string];
    planTier: [] | [{
            Pro: null;
        } | {
            Free: null;
        } | {
            Whale: null;
        }];
}): {
    timezone?: string;
    botPublicKey?: Uint8Array;
    notificationsEnabled: boolean;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
} {
    return {
        timezone: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.timezone)),
        botPublicKey: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.botPublicKey)),
        notificationsEnabled: value.notificationsEnabled,
        accountId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.accountId)),
        name: value.name,
        bot_id: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.bot_id)),
        planTier: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.planTier))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cycles: bigint;
    botStatus: _Status;
    lastHeartbeatAt: _Time;
    cyclesWarning: [] | [string];
    verifiedLicense: boolean;
}): {
    cycles: bigint;
    botStatus: Status;
    lastHeartbeatAt: Time;
    cyclesWarning?: string;
    verifiedLicense: boolean;
} {
    return {
        cycles: value.cycles,
        botStatus: from_candid_Status_n32(_uploadFile, _downloadFile, value.botStatus),
        lastHeartbeatAt: value.lastHeartbeatAt,
        cyclesWarning: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.cyclesWarning)),
        verifiedLicense: value.verifiedLicense
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTimestamp: _Time;
    accountId: _AccountId;
    instrument: string;
    side: _TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp: [] | [_Time];
    entryPrice: number;
    exitPrice: [] | [number];
}): {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
} {
    return {
        entryTimestamp: value.entryTimestamp,
        accountId: value.accountId,
        instrument: value.instrument,
        side: from_candid_TradeSide_n43(_uploadFile, _downloadFile, value.side),
        size: value.size,
        tradeId: value.tradeId,
        exitTimestamp: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.exitTimestamp)),
        entryPrice: value.entryPrice,
        exitPrice: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.exitPrice))
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jwt: string;
    strategies: Array<_StrategyBundle>;
}): {
    jwt: string;
    strategies: Array<StrategyBundle>;
} {
    return {
        jwt: value.jwt,
        strategies: from_candid_vec_n72(_uploadFile, _downloadFile, value.strategies)
    };
}
function from_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryStrategy: bigint;
    paths: Array<_StrategyPath>;
    items: Array<_Strategy>;
    inputSymbol: _Symbol;
    outputSymbol: _Symbol;
}): {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
} {
    return {
        entryStrategy: value.entryStrategy,
        paths: from_candid_vec_n75(_uploadFile, _downloadFile, value.paths),
        items: from_candid_vec_n78(_uploadFile, _downloadFile, value.items),
        inputSymbol: value.inputSymbol,
        outputSymbol: value.outputSymbol
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployedAt: _Time;
    items: Array<_Strategy>;
    pathSymbols: Array<_Symbol>;
}): {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
} {
    return {
        deployedAt: value.deployedAt,
        items: from_candid_vec_n78(_uploadFile, _downloadFile, value.items),
        pathSymbols: value.pathSymbols
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTime: _Time;
    deployedAt: _Time;
    name: string;
    side: _TradeSide;
    priceFeed: _Symbol;
}): {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
} {
    return {
        entryTime: value.entryTime,
        deployedAt: value.deployedAt,
        name: value.name,
        side: from_candid_TradeSide_n43(_uploadFile, _downloadFile, value.side),
        priceFeed: value.priceFeed
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AccountId, _License]): [AccountId, License] {
    return [
        value[0],
        from_candid_License_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        body: string;
        timestamp: bigint;
        statusCode: bigint;
    };
} | {
    err: _BotError;
}): {
    __kind__: "ok";
    ok: {
        body: string;
        timestamp: bigint;
        statusCode: bigint;
    };
} | {
    __kind__: "err";
    err: BotError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_BotError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InvalidUrl: string;
} | {
    FetchFailed: string;
}): {
    __kind__: "InvalidUrl";
    InvalidUrl: string;
} | {
    __kind__: "FetchFailed";
    FetchFailed: string;
} {
    return "InvalidUrl" in value ? {
        __kind__: "InvalidUrl",
        InvalidUrl: value.InvalidUrl
    } : "FetchFailed" in value ? {
        __kind__: "FetchFailed",
        FetchFailed: value.FetchFailed
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Free: null;
} | {
    Whale: null;
}): Variant_Pro_Free_Whale {
    return "Pro" in value ? Variant_Pro_Free_Whale.Pro : "Free" in value ? Variant_Pro_Free_Whale.Free : "Whale" in value ? Variant_Pro_Free_Whale.Whale : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SUSPENDED: null;
} | {
    ACTIVE: null;
}): Status {
    return "SUSPENDED" in value ? Status.SUSPENDED : "ACTIVE" in value ? Status.ACTIVE : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n37(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EXECUTE: null;
} | {
    STANDBY: null;
}): UplinkStatus {
    return "EXECUTE" in value ? UplinkStatus.EXECUTE : "STANDBY" in value ? UplinkStatus.STANDBY : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeSide {
    return "buy" in value ? TradeSide.buy : "sell" in value ? TradeSide.sell : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_SubscriptionTier>;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: Array<SubscriptionTier>;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JwtToken;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: JwtToken;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SubscriptionTier;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: SubscriptionTier;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StrategicVault;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: StrategicVault;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StrategicVault_n70(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InvalidInput: null;
} | {
    LicenseInactive: null;
} | {
    TimestampOutOfWindow: null;
} | {
    InvalidSignature: null;
} | {
    Unauthorized: null;
} | {
    UnknownBotId: null;
} | {
    MissingBotKey: null;
} | {
    ReplayDetected: null;
}): Error_ {
    return "InvalidInput" in value ? Error.InvalidInput : "LicenseInactive" in value ? Error.LicenseInactive : "TimestampOutOfWindow" in value ? Error.TimestampOutOfWindow : "InvalidSignature" in value ? Error.InvalidSignature : "Unauthorized" in value ? Error.Unauthorized : "UnknownBotId" in value ? Error.UnknownBotId : "MissingBotKey" in value ? Error.MissingBotKey : "ReplayDetected" in value ? Error.ReplayDetected : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AccountId, _License]>): Array<[AccountId, License]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrategyBundle>): Array<StrategyBundle> {
    return value.map((x)=>from_candid_StrategyBundle_n73(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrategyPath>): Array<StrategyPath> {
    return value.map((x)=>from_candid_StrategyPath_n76(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Strategy>): Array<Strategy> {
    return value.map((x)=>from_candid_Strategy_n79(_uploadFile, _downloadFile, x));
}
function to_candid_StrategicVault_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategicVault): _StrategicVault {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_StrategyBundle_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategyBundle): _StrategyBundle {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_StrategyPath_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategyPath): _StrategyPath {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_Strategy_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_TradeSide_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): _TradeSide {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountId | null): [] | [_AccountId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone?: string;
    botPublicKey?: Uint8Array;
    notificationsEnabled: boolean;
    accountId?: string;
    name: string;
    bot_id?: string;
    planTier?: Variant_Pro_Free_Whale;
}): {
    timezone: [] | [string];
    botPublicKey: [] | [Uint8Array];
    notificationsEnabled: boolean;
    accountId: [] | [string];
    name: string;
    bot_id: [] | [string];
    planTier: [] | [{
            Pro: null;
        } | {
            Free: null;
        } | {
            Whale: null;
        }];
} {
    return {
        timezone: value.timezone ? candid_some(value.timezone) : candid_none(),
        botPublicKey: value.botPublicKey ? candid_some(value.botPublicKey) : candid_none(),
        notificationsEnabled: value.notificationsEnabled,
        accountId: value.accountId ? candid_some(value.accountId) : candid_none(),
        name: value.name,
        bot_id: value.bot_id ? candid_some(value.bot_id) : candid_none(),
        planTier: value.planTier ? candid_some(to_candid_variant_n50(_uploadFile, _downloadFile, value.planTier)) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jwt: string;
    strategies: Array<StrategyBundle>;
}): {
    jwt: string;
    strategies: Array<_StrategyBundle>;
} {
    return {
        jwt: value.jwt,
        strategies: to_candid_vec_n57(_uploadFile, _downloadFile, value.strategies)
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryStrategy: bigint;
    paths: Array<StrategyPath>;
    items: Array<Strategy>;
    inputSymbol: Symbol;
    outputSymbol: Symbol;
}): {
    entryStrategy: bigint;
    paths: Array<_StrategyPath>;
    items: Array<_Strategy>;
    inputSymbol: _Symbol;
    outputSymbol: _Symbol;
} {
    return {
        entryStrategy: value.entryStrategy,
        paths: to_candid_vec_n60(_uploadFile, _downloadFile, value.paths),
        items: to_candid_vec_n63(_uploadFile, _downloadFile, value.items),
        inputSymbol: value.inputSymbol,
        outputSymbol: value.outputSymbol
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployedAt: Time;
    items: Array<Strategy>;
    pathSymbols: Array<Symbol>;
}): {
    deployedAt: _Time;
    items: Array<_Strategy>;
    pathSymbols: Array<_Symbol>;
} {
    return {
        deployedAt: value.deployedAt,
        items: to_candid_vec_n63(_uploadFile, _downloadFile, value.items),
        pathSymbols: value.pathSymbols
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTime: Time;
    deployedAt: Time;
    name: string;
    side: TradeSide;
    priceFeed: Symbol;
}): {
    entryTime: _Time;
    deployedAt: _Time;
    name: string;
    side: _TradeSide;
    priceFeed: _Symbol;
} {
    return {
        entryTime: value.entryTime,
        deployedAt: value.deployedAt,
        name: value.name,
        side: to_candid_TradeSide_n66(_uploadFile, _downloadFile, value.side),
        priceFeed: value.priceFeed
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryTimestamp: Time;
    accountId: AccountId;
    instrument: string;
    side: TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp?: Time;
    entryPrice: number;
    exitPrice?: number;
}): {
    entryTimestamp: _Time;
    accountId: _AccountId;
    instrument: string;
    side: _TradeSide;
    size: number;
    tradeId: string;
    exitTimestamp: [] | [_Time];
    entryPrice: number;
    exitPrice: [] | [number];
} {
    return {
        entryTimestamp: value.entryTimestamp,
        accountId: value.accountId,
        instrument: value.instrument,
        side: to_candid_TradeSide_n66(_uploadFile, _downloadFile, value.side),
        size: value.size,
        tradeId: value.tradeId,
        exitTimestamp: value.exitTimestamp ? candid_some(value.exitTimestamp) : candid_none(),
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Pro_Free_Whale): {
    Pro: null;
} | {
    Free: null;
} | {
    Whale: null;
} {
    return value == Variant_Pro_Free_Whale.Pro ? {
        Pro: null
    } : value == Variant_Pro_Free_Whale.Free ? {
        Free: null
    } : value == Variant_Pro_Free_Whale.Whale ? {
        Whale: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSide): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeSide.buy ? {
        buy: null
    } : value == TradeSide.sell ? {
        sell: null
    } : value;
}
function to_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StrategyBundle>): Array<_StrategyBundle> {
    return value.map((x)=>to_candid_StrategyBundle_n58(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StrategyPath>): Array<_StrategyPath> {
    return value.map((x)=>to_candid_StrategyPath_n61(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Strategy>): Array<_Strategy> {
    return value.map((x)=>to_candid_Strategy_n64(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
